/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(diner)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(diner)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(kitchen)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(owner)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(owner)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(diner)'}/r/[slug]/cart` | `/r/[slug]/cart`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/menu` | `/r/[slug]/menu`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/wallet` | `/r/[slug]/wallet`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/track/[token]` | `/r/[slug]/track/[token]`, params: Router.UnknownInputParams & { slug: string | number;token: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(diner)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(diner)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(kitchen)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(owner)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(owner)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(diner)'}/r/[slug]/cart` | `/r/[slug]/cart`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `${'/(diner)'}/r/[slug]/menu` | `/r/[slug]/menu`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `${'/(diner)'}/r/[slug]/wallet` | `/r/[slug]/wallet`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `${'/(diner)'}/r/[slug]/track/[token]` | `/r/[slug]/track/[token]`, params: Router.UnknownOutputParams & { slug: string;token: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(diner)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(diner)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(kitchen)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(owner)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(owner)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(diner)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(diner)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(kitchen)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(owner)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(owner)'}` | `/`; params?: Router.UnknownInputParams; } | `${'/(diner)'}/r/${Router.SingleRoutePart<T>}/cart${`?${string}` | `#${string}` | ''}` | `/r/${Router.SingleRoutePart<T>}/cart${`?${string}` | `#${string}` | ''}` | `${'/(diner)'}/r/${Router.SingleRoutePart<T>}/menu${`?${string}` | `#${string}` | ''}` | `/r/${Router.SingleRoutePart<T>}/menu${`?${string}` | `#${string}` | ''}` | `${'/(diner)'}/r/${Router.SingleRoutePart<T>}/wallet${`?${string}` | `#${string}` | ''}` | `/r/${Router.SingleRoutePart<T>}/wallet${`?${string}` | `#${string}` | ''}` | `${'/(diner)'}/r/${Router.SingleRoutePart<T>}/track/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/r/${Router.SingleRoutePart<T>}/track/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(diner)'}/r/[slug]/cart` | `/r/[slug]/cart`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/menu` | `/r/[slug]/menu`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/wallet` | `/r/[slug]/wallet`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `${'/(diner)'}/r/[slug]/track/[token]` | `/r/[slug]/track/[token]`, params: Router.UnknownInputParams & { slug: string | number;token: string | number; } };
    }
  }
}
